title = "Osprey Example Site"
baseURL = "https://tomanistor.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "We deliver the best science content straight to your Facebook wall."
    author = "Toma Nistor"
    description = "Full-stack web developer and UI/UX enthusiast based in San Diego, CA."
    logoBig = "/images/sciencedump2.png"
    logoSmall = "/images/sciencedump2.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "sciencdump"
    linkedin = "tomanistor"
    github = "tomanistor"
    email = ""
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[permalinks]
    gallery = "/" # Redirect gallery index to home page

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Partners"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Top posts"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
